force-app/main/default/objects/Contact/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Home Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <externalId>true</externalId>
    <label>Country Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product Subscription</label>
    <nameField>
        <displayFormat>PS-{00000000}</displayFormat>
        <label>Product Subscription Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Product Subscriptions</relationshipLabel>
    <relationshipName>Product_Subscriptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Subscriptions</relationshipLabel>
    <relationshipName>Product_Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ContactInformationHandler.cls
/**
* This is the handler class to contain helper methods for contact information processing
*
* @author gosingh
*/
public class ContactInformationHandler {
     /**
	 * converts the contact details into the structure defined in 'CustomerDetails' class
	 * @param  aContact contact details
	 * @return Formatted customer info.
	 */
    public static CustomerDetails returnContactDetails(Contact aContact) { 
        if (aContact == null){
            return null;
        }
        
        List<Product__c> products = new List<Product__c>();
        
        for (Product__c p : aContact.Product_Subscriptions__r){
            products.add(p);
        }
        CustomerDetails cd = new CustomerDetails(aContact.Home_Country__r.Country_Code__c, products);
        
        return cd;
    }
    
    /**
    * This is an inner class to define the response structure of contact information
    *
    * @author gosingh
    */
    public class CustomerDetails {
        @testVisible String homeCountry;
        @testVisible List<Product__c> products;
        
        public CustomerDetails (String homeCountry, List<Product__c> products) {
            this.homeCountry = homeCountry;
            this.products = new List<Product__c>(products);
        }
    }
}