force-app/main/default/objects/Contact/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Home Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <externalId>true</externalId>
    <label>Country Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product Subscription</label>
    <nameField>
        <displayFormat>PS-{00000000}</displayFormat>
        <label>Product Subscription Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Product Subscriptions</relationshipLabel>
    <relationshipName>Product_Subscriptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Subscriptions</relationshipLabel>
    <relationshipName>Product_Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ContactSelector.cls
/**
* This is the selector class for Contact Object
*
* @author gosingh
*/
public with sharing class ContactSelector {
    // CONSTANT DECLARATION
    public static final String CONTACT_UUID = 'ContactUUID';
    public static final String CASE_ID = 'CaseId';

    /**
	 * Prepares a query to get contact details based on Id or UUID.
     * @param idValue Id or UUID of customer
	 * @return query string.
	 */
    private static String getContactDetailsById (String idValue) {
        String query = 'SELECT (SELECT ';
        for(Schema.FieldSetMember f : getProductFields()) {
            query += f.getFieldPath() + ', ';
        }
        query += 'Id, Name FROM Product_Subscriptions__r), Id, Name, Home_Country__r.Country_Code__c FROM Contact WHERE UUID__c =: idValue OR Id =: idValue';
        
        return query;
    }

    /**
	 * Prepares a query to get contact details based on related case Id.
     * @param idValue realted CaseId of a customer
	 * @return query string.
	 */
    private static String getContactDetailsByCaseId (String idValue) {
        String query = 'SELECT (SELECT ';
        for(Schema.FieldSetMember f : getProductFields()) {
            query += f.getFieldPath() + ', ';
        }
        query += 'Id, Name FROM Product_Subscriptions__r), Id, Name, Home_Country__r.Country_Code__c FROM Contact WHERE Id IN (SELECT ContactId FROM Case WHERE Id =: idValue)';
        
        return query;
    }

    /**
	 * Queries ContactDetails after preparing query based on input parameters.
     * @param idValue Id, UUID or related CaseId of customer.
     * @param fieldName defines if query should be run based on customerId or caseId
	 * @return customer UUID.
	 */
    public static Contact getContactDetails(String idValue, String fieldName) {
        String query;

        if (String.isBlank(idValue)) {return null;}

        if(fieldName == CONTACT_UUID) {
            query = getContactDetailsById(idValue);
        } else if(fieldName == CASE_ID) {
            query = getContactDetailsByCaseId(idValue);
        } else {
            return null;
        }

        List<Contact> contacts = new List<Contact>();
        try{
            contacts = Database.query(query);
        } catch(Exception e) {
            system.debug('Exception: '+e);
        }
        
        return (contacts.isEmpty() ? null : contacts.get(0));
    }

    /**
	 * Retreives fields from 'Basic' fieldset of Product__c object
	 * @return customer UUID.
	 */
    private static List<Schema.FieldSetMember> getProductFields() {
        return SObjectType.Product__c.FieldSets.Basic.getFields();
    }
}
    