force-app/main/default/objects/Contact/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Home Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <externalId>true</externalId>
    <label>Country Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Country__c/fields/Currency_ISO_Code__c.field-meta.xml
<CustomField>
    <fullName>Currency_ISO_Code__c</fullName>
    <label>Currency ISO Code</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product Subscription</label>
    <nameField>
        <displayFormat>PS-{00000000}</displayFormat>
        <label>Product Subscription Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Product Subscriptions</relationshipLabel>
    <relationshipName>Product_Subscriptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Subscriptions</relationshipLabel>
    <relationshipName>Product_Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CustomerController_Test.cls
@isTest()
public class CustomerController_Test {
    static Country__c testCountry;
    static Product2 sampleProduct;
    static Contact testContact;
    static Case testCase;
    static Product__c subscription;

    public static void makeData() {
        testCountry = new Country__c(Name = 'United Kingdom',
                                        Country_Code__c = 'UK',
                                        Currency_ISO_Code__c = 'GBP'
                                    );
        sampleProduct = new Product2(StockKeepingUnit = 'UT01TEST',
                                        Name = 'Sample',
                                        Family = 'Standard'
                                    );
        insert testCountry;
        insert sampleProduct;

        testContact = new Contact(FirstName = 'Unit',
                                    LastName = 'TestContact',
                                    Email = 'unit@test.ex.co.ut',
                                    Home_Country__c = testCountry.Id,
                                    UUID__c = 'UT123'
                                );

        insert testContact;

        subscription = new Product__c ( Contact__c = testContact.Id,
                                        Product__c = sampleProduct.Id
                                    );
        
        insert subscription;
    }

    @IsTest
    static void test_getCustomerInfo_validCaseId() {
        makeData();

        testCase = new Case (ContactId = testContact.Id,
                            Status = 'New',
                            Subject = 'UnitTest');
        insert testCase;

        Test.startTest();
            String response = CustomerController.getCustomerInfo(testCase.Id);
        Test.stopTest();

        ContactInformationHandler.CustomerDetails customerDetail = (ContactInformationHandler.CustomerDetails)JSON.deserialize(response, ContactInformationHandler.CustomerDetails.class);
        System.assertEquals('UK', customerDetail.homeCountry);
        System.assertEquals('Sample', customerDetail.products[0].Product_Name__c);
    }

    @IsTest
    static void test_getCustomerInfo_inValidCaseId() {
        makeData();

        Test.startTest();
            String response = CustomerController.getCustomerInfo(testCountry.Id);
        Test.stopTest();
        system.debug(response);
        ContactInformationHandler.CustomerDetails customerDetail = (ContactInformationHandler.CustomerDetails)JSON.deserialize(response, ContactInformationHandler.CustomerDetails.class);
        system.debug(customerDetail);
        System.assertEquals(null, customerDetail);
        
    }

    @IsTest
    static void test_getCustomerInfo_nullCaseId() {
        makeData();
        Test.startTest();
            String response =  CustomerController.getCustomerInfo(null);
        Test.stopTest();

        System.assertEquals(null, response);
        
    }
}